services:
  accommodation-reservation:
    build: .
    image: ${DOCKERHUB_USERNAME:-pop2bubble}/${IMAGE_NAME:-accommodation-reservation}:${TAG:-latest}
    container_name: accommodation-reservation
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    restart: unless-stopped
