apiVersion: v1
kind: Service
metadata:
  name: accommodation-reservation
  labels:
    app: accommodation-reservation
spec:
  type: LoadBalancer
  selector:
    app: accommodation-reservation
  ports:
    - name: http
      port: 80
      targetPort: 8080
